
JSONCPP_PATH:=$(lib_path)/json-cpp
JSONCPP_INC:=-I$(JSONCPP_PATH)
JSONCPP_LIB:=-L$(JSONCPP_PATH) -ljsoncpp

JSONF90_PATH:=$(lib_path)/json-f90
JSONF90_INC:=-I$(JSONF90_PATH)
JSONF90_LIB:=-L$(JSONF90_PATH) -ljsonf90

LAPACK_PATH:=
LAPACK_INC:=
LAPACK_LIB:=-llapack -lblas

OPENMPI_PATH:=
OPENMPI_INC:=-I/usr/include/openmpi
OPENMPI_LIB:=

PARMETIS_PATH:=$(lib_path)/ParMetis-3.1.1 $(HOME)/bin/ParMetis-3.1.1
PARMETIS_INC:=$(foreach p, $(PARMETIS_PATH), -I$(p))
PARMETIS_LIB:=$(foreach p, $(PARMETIS_PATH), -L$(p)) -lparmetis -lmetis

PARMS_PATH:=$(lib_path)/pARMS_3.3 $(HOME)/bin/pARMS_3.3
PARMS_INC:=$(foreach p, $(PARMS_PATH), -I$(p)/include)
PARMS_LIB:=$(foreach p, $(PARMS_PATH), -L$(p)/lib) -lparms
PARMS_FLG:=-D"USE_MPI" -D"REAL=double" -D"DBL" -D"HAS_BLAS" -D"FORTRAN_UNDERSCORE" -D"VOID_POINTER_SIZE_8"


# INC+=$(PARMS_INC) $(OPENMPI_INC) $(LAPACK_INC) $(PARMETIS_INC) $(JSONCPP_INC) $(JSONF90_INC)
# LIB+=$(PARMS_LIB) $(OPENMPI_LIB) $(LAPACK_LIB) $(PARMETIS_LIB) $(JSONCPP_LIB) $(JSONF90_LIB)

# FC_MPI_LINK:=$(shell $(FC_MPI) -showme:link)
# LIB+=-lgfortran -lm
# FLG+=-D"USE_MPI"
